// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/log;
import ballerina/http;
import ballerina/test;

configurable ApiKeysConfig & readonly apiKeyConfig = ?;
Client charityCheckPDFClient = check new Client(apiKeyConfig, serviceUrl = "https://apidata.guidestar.org/charitycheckpdf");

@test:Config {
    enable: false
}
function testCharitycheckpdf() returns error? {
    log:printInfo("charityCheckPDFClient -> testCharitycheckpdf()");
    http:Response result = check charityCheckPDFClient->/v1/pdf/["13-1837418"];
    test:assertEquals(result.getContentType(), "application/pdf");
}
