// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/log;
import ballerina/test;
import ballerina/io;

configurable ApiKeysConfig & readonly apiKeyConfig = ?;
Client premierClient = check new Client(apiKeyConfig, serviceUrl = "https://api.candid.org/premier");

@test:Config {}
function testPremierV1() {
}

@test:Config {}
function testPremierV1Propdf() {
}

@test:Config {}
function testPremierV1ftapdf() {
}

@test:Config {}
function testPremierV2() {
}

@test:Config {}
function testPremierV3() returns error? {
    log:printInfo("premierClient -> testPremierV3()");
    V3PublicProfile result = check premierClient->/v3/["13-1837418"];
    io:println(result);
}
