// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/log;
import ballerina/http;
import ballerina/os;
import ballerina/test;

configurable string apiKey = os:getEnv("PREMIER_API_KEY");

const EIN = "13-1837418";

ApiKeysConfig apiKeyConfig = {
    subscriptionKey: apiKey
};
Client premier = check new Client(apiKeyConfig, serviceUrl = "https://api.candid.org/premier");

@test:Config {
    enable: false
}
function testPremierV1Propdf() returns error? {
    log:printInfo("premier -> testPremierV1Propdf()");
    http:Response result = check premier->/v1/propdf/[EIN];
    test:assertEquals(result.getContentType(), "application/pdf");
}

@test:Config {
    enable: false
}
function testPremierV1ftapdf() returns error? {
    log:printInfo("premier -> testPremierV1ftapdf()");
    http:Response result = check premier->/v1/ftapdf/[EIN];
    test:assertEquals(result.getContentType(), "application/pdf");
}

@test:Config {
    enable: false
}
function testPremierV3() returns error? {
    log:printInfo("premier -> testPremierV3()");
    V3PublicProfile result = check premier->/v3/[EIN];
    V3PublicProfile_data? data = result?.data;
    if data is V3PublicProfile_data {
        Summary3? summary = data?.summary;
        if summary is Summary3 {
            test:assertEquals(summary?.ein, EIN);
        } else {
            test:assertFail();
        }
    } else {
        test:assertFail();
    }
}
