// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/test;

configurable ApiKeysConfig & readonly apiKeyConfig = ?;
Client baseClient = check new Client(apiKeyConfig, serviceUrl = "https://api.candid.org/premier");

@test:Config {}
isolated function  testPremier_v1() {
}

@test:Config {}
isolated function  testPremier_v1_propdf() {
}

@test:Config {}
isolated function  testPremier_v1_ftapdf() {
}

@test:Config {}
isolated function  testPremier_v2() {
}

@test:Config {}
isolated function  testPremier_v3() {
}
