// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/test;

configurable ApiKeysConfig & readonly apiKeyConfig = ?;
Client baseClient = check new Client(apiKeyConfig, serviceUrl = "https://api.candid.org/essentials");

@test:Config {}
isolated function  testEssentials_v1() {
}

@test:Config {}
isolated function  testEssentials_v2() {
}

@test:Config {}
isolated function  testEssentials_v3() {
}

@test:Config {}
isolated function  testEssentials_lookup() {
}

@test:Config {}
isolated function  testEssentials_lookup_filter_name() {
}

@test:Config {}
isolated function  testEssentials_lookup_filter_name_key_or_value() {
}
